package com.kevinraupp.studyws.services.exceptions;

public class ResourceWithContentFoundException extends RuntimeException{
    public ResourceWithContentFoundException(Object id){
        super("Resource with content, canÂ´t delete. Id: " + id);
    }
}
